museum/__init__.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from flask import Flask

from . import views
from .extensions import mongo


def create_app(config=None):
    app = Flask(__name__)

    # config
    app.config.from_object(config)

    # database
    mongo.init_app(app)

    # blueprint
    app.register_blueprint(views.bp_home)
    app.register_blueprint(views.bp_masterpiece)
    app.register_blueprint(views.bp_author)
    app.register_blueprint(views.bp_device)

    return app

museum/views/__init__.py
from .home import bp_home
from .masterpiece import bp_masterpiece
from .author import bp_author
from .device import bp_device

museum/views/author.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask import Blueprint, render_template, redirect, url_for, abort, request
import pymongo
from bson.objectid import ObjectId

from ..extensions import mongo


bp_author = Blueprint('author', __name__, url_prefix='/author')


@bp_author.route('/')
def show_authors():
    authors = mongo.db.authors.find().sort([('name', pymongo.ASCENDING)])
    return render_template('authors.html', authors=authors)


@bp_author.route('/add/', methods=['GET', 'POST'])
def add_author():
    if request.method == 'POST':
        data = dict()
        name = request.form.get('name')
        if name:
            data['name'] = name
        other_names = request.form.getlist('other-names')
        other_names = filter(lambda x: x, other_names)
        if other_names:
            data['other_names'] = other_names
        email = request.form.get('email')
        if email:
            data['email'] = email
        qq = request.form.get('qq')
        if qq:
            data['qq'] = qq
        realname = request.form.get('realname')
        if realname:
            data['realname'] = realname
        site = request.form.get('site')
        if site:
            data['site'] = site
        address = request.form.get('address')
        if address:
            data['address'] = address
        zip_ = request.form.get('zip')
        if zip_:
            data['zip'] = zip_
        print data

        mongo.db.authors.insert_one(data)
        return redirect(url_for('author.show_authors'))

    offset = request.args.get('offset')
    if offset:
        if not offset.isdigit():
            abort(400)
        offset = int(offset)
        authors = mongo.db.masterpieces.distinct('author')
        old_author = authors[offset]
    else:
        old_author = dict()

    return render_template('author_add.html', old_author=old_author)


@bp_author.route('/<oid>/edit/', methods=['GET', 'POST'])
def edit_author(oid):
    author = mongo.db.authors.find_one({'_id': ObjectId(oid)})
    if not author:
        abort(404)

    if request.method == 'POST':
        data = dict()
        name = request.form.get('name')
        if name:
            data['name'] = name
        other_names = request.form.getlist('other_names')
        if other_names:
            data['other_names'] = other_names
        email = request.form.get('email')
        if email:
            data['email'] = email
        qq = request.form.get('qq')
        if qq:
            data['qq'] = qq
        realname = request.form.get('realname')
        if realname:
            data['realname'] = realname
        site = request.form.get('site')
        if site:
            data['site'] = site
        address = request.form.get('address')
        if address:
            data['address'] = address
        zip_ = request.form.get('zip')
        if zip_:
            data['zip'] = zip_

        mongo.db.authors.update_one({'_id': ObjectId(oid)}, {'$set': data})
        return redirect(url_for('author.show_authors'))

    offset = request.args.get('offset')
    if offset:
        if not offset.isdigit():
            abort(400)
        offset = int(offset)
        authors = mongo.db.masterpieces.distinct('author')
        old_author = authors[offset]
    else:
        old_author = dict()

    return render_template('author_edit.html', author=author, old_author=old_author)


@bp_author.route('/<oid>/')
def show_author_detail(oid):
    author = mongo.db.authors.find_one({'_id': ObjectId(oid)})
    if not author:
        abort(404)

    masterpieces = mongo.db.masterpieces.find({'author_oid': ObjectId(oid)})
    author['masterpieces'] = masterpieces
    # print author['masterpieces']
    return render_template('author_detail.html', author=author)

museum/views/device.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
from bson.objectid import ObjectId
import datetime

from flask import Blueprint, render_template, redirect, url_for, abort, request
from flask import current_app, send_from_directory, send_file
import pymongo


from ..extensions import mongo
from ..helpers import get_client_ip, get_user_agent


bp_device = Blueprint('device', __name__, url_prefix='/device')


@bp_device.route('/')
def show_devices():
    devices = mongo.db.devices.find()
    return render_template('devices.html', devices=devices)


@bp_device.route('/<oid>/')
def show_device_detail(oid):
    device = mongo.db.devices.find_one({'_id': ObjectId(oid)})
    if not device:
        abort(404)
    return render_template('device_detail.html', device=device)


@bp_device.route('/<oid>/preview/')
def get_device_preview(oid):
    device = mongo.db.devices.find_one({'_id': ObjectId(oid)})
    if not device:
        abort(404)

    if 'pictures' in device and device['pictures']:
        filename = device['pictures'][0]
        path = os.path.join('devices', device['brand'], device['model'], filename)
        return send_file(os.path.join(current_app.config['ASSETS_DIR'], path))
    else:
        path = os.path.join(current_app.static_folder, 'default.bmp')
        return send_file(path)


@bp_device.route('/<oid>/picture/<int:idx>/')
def get_device_picture(oid, idx):
    device = mongo.db.devices.find_one({'_id': ObjectId(oid)})
    if not device:
        abort(404)

    if 'pictures' in device and idx <= len(device['pictures']):
        filename = device['pictures'][idx]
    else:
        abort(404)

    path = os.path.join('devices', device['brand'], device['model'], filename)
    return send_file(os.path.join(current_app.config['ASSETS_DIR'], path))
    # return send_from_directory(current_app.config['ASSETS_DIR'], filename=path)


def _get_device_dirname(device):
    return os.path.abspath(os.path.join(current_app.config['ASSETS_DIR'], 'devices', device['brand'], device['model']))


@bp_device.route('/<oid>/update/')
def update_device_pictures(oid):
    device = mongo.db.devices.find_one({'_id': ObjectId(oid)})
    if not device:
        abort(404)

    pictures = []

    for filename in os.listdir(_get_device_dirname(device)):
        ext = os.path.splitext(filename)[-1].lower()
        if ext in ['.bmp', '.jpg', '.png', '.gif']:
            pictures.append(filename)
        else:
            continue

    print pictures

    mongo.db.devices.update_one({'_id': ObjectId(oid)}, {'$set': {'pictures': pictures}})
    return redirect(url_for('device.show_device_detail', oid=oid))


@bp_device.route('/add/', methods=['GET', 'POST'])
def add_device():
    if request.method == 'POST':
        brand = request.form.get('brand')
        model = request.form.get('model')
        if not brand or not model:
            return redirect(url_for('device.add_device'))
        data = dict(brand=brand, model=model)
        alias = request.form.get('alias')
        if alias:
            data['alias'] = alias
        dimension = request.form.getlist('dimension')
        dimension = filter(lambda x: x, dimension)
        if dimension:
            data['dimension'] = map(lambda x: float(x), dimension)
        net_weight = request.form.get('net-weight')
        if net_weight:
            data.setdefault('weight', dict())
            data['weight']['net_weight'] = float(net_weight)
        with_battery_weight = request.form.get('with-battery-weight')
        if with_battery_weight:
            data.setdefault('weight', dict())
            data['weight']['with_battery_weight'] = float(with_battery_weight)
        screen = request.form.getlist('screen')
        screen = filter(lambda x: x, screen)
        if len(screen) == 2:
            data['screen'] = map(lambda x: int(x), screen)
        battery = request.form.get('battery')
        if battery:
            data['battery'] = battery
        print data

        result = mongo.db.devices.insert_one(data)
        print result.inserted_id
        device = mongo.db.devices.find_one({'_id': ObjectId(result.inserted_id)})
        os.makedirs(_get_device_dirname(device))

        return redirect(url_for('device.show_device_detail', oid=result.inserted_id))

    copy_oid = request.args.get('copy')
    if copy_oid:
        copy_device = mongo.db.devices.find_one({'_id': ObjectId(copy_oid)})
        if not copy_device:
            abort(400)
    else:
        copy_device = dict()

    return render_template('device_add.html', device=copy_device)


@bp_device.route('/<oid>/edit/', methods=['GET', 'POST'])
def edit_device(oid):
    device = mongo.db.devices.find_one({'_id': ObjectId(oid)})
    if not device:
        abort(404)

    if request.method == 'POST':
        brand = request.form.get('brand')
        model = request.form.get('model')
        if not brand or not model:
            return redirect(url_for('device.edit_device'))
        data = dict(brand=brand, model=model)
        alias = request.form.get('alias')
        if alias:
            data['alias'] = alias
        dimension = request.form.getlist('dimension')
        dimension = filter(lambda x: x, dimension)
        if len(dimension) == 3:
            data['dimension'] = map(lambda x: float(x), dimension)
        net_weight = request.form.get('net-weight')
        if net_weight:
            data.setdefault('weight', dict())
            data['weight']['net_weight'] = float(net_weight)
        with_battery_weight = request.form.get('with-battery-weight')
        if with_battery_weight:
            data.setdefault('weight', dict())
            data['weight']['with_battery_weight'] = float(with_battery_weight)
        screen = request.form.getlist('screen')
        screen = filter(lambda x: x, screen)
        if len(screen) == 2:
            data['screen'] = map(lambda x: int(x), screen)
        battery = request.form.get('battery')
        if battery:
            data['battery'] = battery
        print data

        mongo.db.devices.update_one({'_id': ObjectId(oid)}, {'$set': data})
        new_device = mongo.db.devices.find_one({'_id': ObjectId(oid)})

        old_dirname, new_dirname = _get_device_dirname(device), _get_device_dirname(new_device)
        if new_dirname != old_dirname:
            os.renames(old_dirname, new_dirname)

        return redirect(url_for('device.show_device_detail', oid=oid))

    return render_template('device_edit.html', device=device)


@bp_device.route('/<oid>/delete/')
def delete_device(oid):
    device = mongo.db.devices.find_one_and_delete({'_id': ObjectId(oid)})
    os.removedirs(_get_device_dirname(device))
    return redirect(url_for('device.show_devices'))

museum/views/home.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask import Blueprint, render_template, redirect, url_for, abort, request


bp_home = Blueprint('home', __name__)


@bp_home.route('/')
def index():
    return redirect(url_for('masterpiece.show_masterpieces'))


@bp_home.route('/about-me/')
def show_about_me():
    return render_template('about_me.html')


@bp_home.route('/recycling/')
def show_recovery():
    return render_template('recycling.html')

museum/templates/_base.html
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta https-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="文曲星博物馆">
        <meta name="keywords" content="文曲星博物馆">
        <meta name="author" content="whypro">

        <title>文曲星博物馆 | {% block title %}{% endblock %}</title>

        <!-- 新 Bootstrap 核心 CSS 文件 -->
        {#
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/themes/google-plus/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/themes/google-plus/style.css') }}">
        #}

        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">

        {#
        <!-- 可选的Bootstrap主题文件（一般不用引入） -->
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        #}

        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

        <link rel="apple-touch-icon" href="{{ url_for('static', filename='apple-touch-icon.png') }}">
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    </head>
    <body>
        <div class="container-fluid">
            {% include '_header.html' %}
        </div>

        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <div class="container">
            {% include '_footer.html' %}
        </div>

        <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
        {#
        <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
        #}
        <script src="{{ url_for('static', filename='jquery/jquery-1.11.3.min.js') }}"></script>

        <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
        <script src="{{ url_for('static', filename='bootstrap/bootstrap.min.js') }}"></script>
        {#
        <script src="{{ url_for('static', filename='bootstrap/themes/google-plus/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/themes/google-plus/scripts.js') }}"></script>
        <script src="https://cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        #}

        <script src="{{ url_for('static', filename='script.js') }}"></script>

    </body>
</html>

museum/templates/_footer.html
            <div class="row">
                <div class="col-md-12">
                    <hr />
                    <p class="text-center"><small>关于我们 · 联系我们 · 免责声明 · 帮助中心 · 移动应用</small></p>
                    <p class="text-center">
                        <small>&copy;2015 WQX-Museum, all rights reserved</small>
                    </p>
                </div>
            </div>

museum/templates/_header.html
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#museum-menu" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url_for('home.index') }}">文曲星博物馆</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="museum-menu">
                        <ul class="nav navbar-nav">
                            <li><a href="{{ url_for('home.index') }}">首页 <span class="sr-only">(current)</span></a></li>
                            <li><a href="{{ url_for('masterpiece.show_masterpieces') }}">作品管理</a></li>
                            <li><a href="{{ url_for('author.show_authors') }}">作者管理</a></li>
                            <li><a href="{{ url_for('device.show_devices') }}">机型管理</a></li>
                            <li><a href="{{ url_for('home.show_recovery') }}">旧机回收</a></li>
                            <li><a href="{{ url_for('home.show_about_me') }}">关于我</a></li>
                            {#
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                            #}
                        </ul>
                        {#
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">管理 <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">修改资料</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">注销</a></li>
                                </ul>
                            </li>
                        </ul>
                        #}
                        <form class="navbar-form navbar-right hidden-sm" role="search" id="search-form">
                            <div class="form-group">
                                <label class="sr-only" for="key">Key</label>
                                <input id="search-key" name="key" type="text" class="form-control" placeholder="请输入关键词……">
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>

museum/templates/about_me.html
{% extends '_base.html' %}
{% block title %}关于我{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>关于我</h3>
                    </div>
                    <div>
                        <p>
                            时光如水，岁月如歌。与大部分 80、90 后一样，文曲星已经成为了我们高中时代最美好的记忆。
                            <br>
                            课堂上、放学后、多少个不眠之夜，我们都调试着 GVBASIC 程序，编译着 LAVA 代码，探究着 6502 的奥秘。
                            <br>
                            而如今，恐怕已经没有多少人在停留在这里了。
                        </p>
                        <p>
                            在星星世界里，我是一个无名小卒。但是怀着一颗赤诚的心，建立了本站，供各位朋友浏览、下载和回忆。
                            <br>
                            但作品数量的庞大，也让我有心无力。
                            <br>
                            本站尊重任何人的版权，如果您觉得个别图片、程序或者源码侵犯了您的版权，请及时联系我移除以保护您的权益。同时如果您发现条目信息有误，请及时联系我予以改正。（我的邮箱：whypro#live.cn）
                        </p>
                        <p>
                            如果您支持本站，请慷慨赞助。您的支持是我最大的动力！（我的支付宝账户：whypro#live.cn）
                        </p>
                        <p>
                            创建于 2015-10-23
                            <br>
                            更新于 2016-03-03
                            <br>
                            By <b>whypro</b>

                        </p>
                    </div>
                </div>

            </div>
{% endblock %}

museum/templates/author_add.html
{% extends '_base.html' %}
{% block title %}添加作者{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>添加作者</h3>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <form class="form-horizontal" method="post" action="{{ url_for('author.add_author') }}">

                        <div class="form-group">
                            <label for="name-input" class="col-sm-2 control-label">用户名</label>
                            <div class="col-sm-10">
                                <input type="text" name="name" class="form-control" id="name-input">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="other-names-input" class="col-sm-2 control-label">别名</label>
                            <div class="col-sm-10">
                                <input type="text" name="other-names" class="form-control" id="other-names-input">
{#                                <br>#}
{#                                <input type="text" name="other-names" class="form-control" id="other-names-input-1">#}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email-input" class="col-sm-2 control-label">邮箱</label>
                            <div class="col-sm-10">
                                <input type="text" name="email" class="form-control" id="email-input">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="qq-input" class="col-sm-2 control-label">QQ</label>
                            <div class="col-sm-10">
                                <input type="text" name="qq" class="form-control" id="qq-input">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="realname-input" class="col-sm-2 control-label">姓名</label>
                            <div class="col-sm-10">
                                <input type="text" name="realname" class="form-control" id="realname-input">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="site-input" class="col-sm-2 control-label">网站</label>
                            <div class="col-sm-10">
                                <input type="text" name="site" class="form-control" id="site-input">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="address-input" class="col-sm-2 control-label">地址</label>
                            <div class="col-sm-10">
                                <input type="text" name="address" class="form-control" id="address-input">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="zip-input" class="col-sm-2 control-label">邮编</label>
                            <div class="col-sm-10">
                                <input type="text" name="zip" class="form-control" id="zip-input">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">作者</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">
                                    {% for k, v in old_author.items() %}
                                    {{ k }}: {{ v }}{% if not loop.last %}, {% endif %}
                                    {% endfor %}
                                </p>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">保存</button>&emsp;
                                <a class="btn btn-default" href="{{ url_for('author.show_authors') }}">取消</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
{% endblock %}

museum/templates/device_detail.html
{% extends '_base.html' %}
{% block title %}{{ device.brand~' '~device.model }}{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>{{ device.brand~' '~device.model }}</h3>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h4>硬件信息</h4>
                    <div class="row">
                        <ul>
                            <li>品牌：{{ device.brand|d('未知') }}</li>
                            <li>型号：{{ device.model|d('未知') }}</li>
                            {% set score = masterpiece.marking.score|int if 'marking' in masterpiece and 'score' in masterpiece.marking and masterpiece.marking.score else None %}
                            <li>评分：
                            {%- if score == None %}N/A{% else %}
                            {%- for i in range(score) %}★{% endfor -%}
                            {%- for i in range(5-score) %}☆{% endfor -%}
                            {% endif -%}
                            </li>
                            <li>三维：{{ device.dimension|join('*') if device.dimension else '未知' }} mm</li>
                            {% if device.weight %}<li>重量：{{ device.weight['net_weight']|d('未知') }} g, {{ device.weight['with_battery_weight']|d('未知') }} g（含电池）</li>{% endif %}
                            <li>电池：{{ device.battery|d('未知') }}</li>
                        </ul>
                    </div>

                    {% if 'pictures' in device and device.pictures %}
                    <h4>实物图片</h4>
                    <div class="row">
                        {% for picture in device.pictures %}
                        <div class="thumbnail col-md-2 col-sm-4 col-xs-12">
                            <a href="{{ url_for('device.get_device_picture', oid=device._id, idx=loop.index0) }}"><img src="{{ url_for('device.get_device_picture', oid=device._id, idx=loop.index0) }}" class="img-responsive" /></a>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                    <hr>
                    <div class="col-md-12">
                        <a class="btn btn-success" href="{{ url_for('device.edit_device', oid=device._id) }}">修改</a>&emsp;
                        <a class="btn btn-warning" href="{{ url_for('device.update_device_pictures', oid=device._id) }}">更新截图和文件</a>&emsp;
                        <a class="btn btn-primary" href="{{ url_for('device.add_device', copy=device._id) }}">复制</a>&emsp;
                        <a class="btn btn-danger" href="{{ url_for('device.delete_device', oid=device._id) }}" onclick="return confirm('删除将不可恢复。确定删除吗？');">删除</a>
                    </div>
                </div>
            </div>
{% endblock %}

museum/templates/devices.html
{% extends '_base.html' %}
{% block title %}机型管理{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>所有机型</h3>
                    </div>
                    <hr>
                </div>

                {% for device in devices %}
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="thumbnail">
                        <a href="{{ url_for('device.show_device_detail', oid=device._id) }}">
                            <img alt="{{ device.model }}" src="{{ url_for('device.get_device_preview', oid=device._id) }}" class="img-responsive" style="height: 200px; display: block;"/>
                        </a>
                        <div class="caption">
                            <h4 class="text-center">{{ device.brand~' '~device.model }}</h4>
                            <p>
                                {% set score = device.marking.score|int if 'marking' in device and 'score' in device.marking and device.marking.score else None %}
                                <small>评分：
                                    {%- if score == None %}N/A{% else %}
                                    {%- for i in range(score) %}★{% endfor -%}
                                    {%- for i in range(5-score) %}☆{% endfor -%}
                                    {% endif -%}
                                </small>
                                <br>
                            </p>
                            <p>{{ device.description|d('') }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
{% endblock %}

museum/templates/recovery.html
{% extends '_base.html' %}
{% block title %}旧机回收{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>旧机回收</h3>
                    </div>
                    <div>
                        <p>
                            如果您想转让爱机，请将【型号】【成色】【图片附件】等信息发送至 whypro#live.cn。
                        </p>
                    </div>
                </div>

            </div>
{% endblock %}

museum/templates/recycling.html
{% extends '_base.html' %}
{% block title %}旧机回收{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>旧机回收</h3>
                    </div>
                    <div>
                        <p>
                            如果您想转让爱机，请将【型号】【成色】【图片附件】等信息发送至 whypro#live.cn。
                        </p>
                    </div>
                </div>

            </div>
{% endblock %}